name: Deploy Landing Page

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: gulp build --env prod

      - name: Clean server directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Cleaning target directory..."
            rm -rf /var/www/sms.infiniasync.com/html/*
            echo "Clean complete."
            # Preserve any hidden files (like .htaccess) if needed
            # find /var/www/sms.infiniasync.com/html/ -type f -not -name '.*' -delete

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/sms.infiniasync.com/html"
          strip_components: 1

      - name: Set correct permissions
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Setting permissions..."
            chown -R www-data:www-data /var/www/sms.infiniasync.com/html
            find /var/www/sms.infiniasync.com/html -type d -exec chmod 755 {} \;
            find /var/www/sms.infiniasync.com/html -type f -exec chmod 644 {} \;
            echo "Permissions updated."